---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#############################
# Start the job on all push #
#############################
on:
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
      - name: Bash shell beautifier
        # You may pin to the exact commit or the version.
        # uses: illvart/beautysh-action@b97bb857aa544ac5e02aecbe84a2ee6ec0fd91b7
        uses: illvart/beautysh-action@v1.0.0
